""" file for testing the diamond rule """
from agent.game_state import State

state = State("red", 5)
state.update("red", ("PLACE", 3, 0))
state.update("red", ("PLACE", 3, 1))
state.update("blue", ("PLACE", 4, 0))
state.print_state()
state.update("blue", ("PLACE", 2, 1))
print("checking diamond rule:")
state.print_state()

print('================================================')
state = State("red", 5)
state.update("red", ("PLACE", 4, 1))
state.update("red", ("PLACE", 2, 4))
state.update("red", ("PLACE", 0, 3))
state.update("red", ("PLACE", 3, 0))
state.update("red", ("PLACE", 1, 1))
state.update("red", ("PLACE", 3, 3))
state.update("red", ("PLACE", 1, 4))
state.update("blue", ("PLACE", 3, 1))
state.update("blue", ("PLACE", 3, 2))
state.update("blue", ("PLACE", 2, 3))
state.update("blue", ("PLACE", 1, 3))
state.update("blue", ("PLACE", 1, 2))
state.update("blue", ("PLACE", 2, 1))
state.print_state()
state.update("red", ("PLACE", 2, 2))
print("checking diamond rule:")
state.print_state()
